name: group10_environment
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - numpy=1.22.*
  - altair=4.1.*
  - python=3.9.*
  - pytest = 8.1.1 *
  - pip:
    - pycrimeprediction==0.1.0


