name: group10_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.0
  - pandas=2.2.0
  - scikit-learn=1.4.1.post1
  - altair=5.2.0
  - altair_saver=0.5.0 
  - conda=24.1.2 
  - python=3.11.7
